src/ShortLinks.WebMVC/Controllers/ShortLinkController.cs
using Microsoft.AspNetCore.Mvc;
using ShortLinks.BLL.Services.Interfaces;
using System.Threading.Tasks;

namespace ShortLinks.WebMVC.Controllers
{
    public class ShortLinkController : Controller
    {
        private readonly ILinkService _linkService;

        public ShortLinkController(ILinkService linkService)
        {
            _linkService = linkService;
        }

        [HttpGet]
        [Route("l")]
        public async Task<IActionResult> RedirectToOldLink(int id)
        {
            if (!await _linkService.IsLinkExistAsync(id))
            {
                return NotFound();
            }

            var link = await _linkService.GetLinkAsync(id);
            if (link.IsActive)
            {
                await _linkService.IncreaseInQuantityAsync(id);
                return Redirect(link.OldLink);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

src/ShortLinks.WebMVC/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShortLinks.BLL.Services.Interfaces;
using System.Threading.Tasks;

namespace ShortLinks.WebMVC.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {
        private readonly IStatisticsService _statisticsService;
        private readonly IPersonalDataProtectionService _personalDataProtectionService;

        public StatisticsController(
            IStatisticsService statisticsService,
            IPersonalDataProtectionService personalDataProtectionService)
        {
            _statisticsService = statisticsService;
            _personalDataProtectionService = personalDataProtectionService;
        }

        [HttpGet]
        public async Task<IActionResult> Show()
        {
            var projects = await _statisticsService.GetTopProjectsAsync(User);
            ViewBag.Projects = new SelectList(projects, "Id", "Caption");

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AllLinks()
        {
            var linkStatistics = await _statisticsService.GetOrderedUserLinksAsync(User);
            return View(linkStatistics);
        }

        [HttpGet]
        public async Task<IActionResult> LinksByProject(int projectId)
        {
            if (_personalDataProtectionService.IsUserHasProject(projectId, User))
            {
                var linkStatistics = await _statisticsService.GetOrderedLinksByProjectAsync(projectId);
                return View(linkStatistics);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<IActionResult> AllProjects()
        {
            var projectStatistics = await _statisticsService.GetOrderedProjects(User);
            return View(projectStatistics);
        }

        [HttpGet]
        public async Task<IActionResult> ShowDiagram()
        {
            var links = await _statisticsService.GetLinksAsync(User);
            return View(links);
        }
    }
}

src/ShortLinks.WebMVC/Views/Statistics/AllLinks.cshtml
@model LinkStatisticsModel
@{

    ViewData["Title"] = "Статистика";
}

<div class="col">
    <br />
    <div class="text-center m-sm-1">
        <p class="display-3">Общая статистика по ссылкам</p>
        <p>В статистике представленны только ваши ссылки, которые существуют на данный момент</p>
    </div>
    <br />
    <div class=" card ">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <a class="btn-collapse " data-toggle="collapse" href="#generalInfo" role="button" aria-expanded="false" aria-controls="generalInfo">
                    Показать общую статистику <i class="fas fa-chevron-down"></i>
                </a>
            </h5>
        </div>
        <div class=" font-weight-bold collapse" id="generalInfo">
            <div class=" card-body">
                <p>Общее количество ссылок: <text class="text-success">@Model.LinkCount</text> </p>
                <p>Общее количество открытых ссылок: <text class="text-success">@Model.PublicLinkCount</text></p>
                <p>Общее количество активных ссылок: <text class="text-success">@Model.ActiveLinkCount</text></p>
                <p>Общее количество переходов: <text class="text-success">@Model.TotalUseAmount</text></p>
                <p>Время создания первой существующей ссылки: <text class="text-success">@Model.FirstLinkDate.ToString("dd-MM-yyyy HH:mm:ss")</text></p>
                <p>Время создания последней существующей ссылки: <text class="text-success">@Model.LastLinkDate.ToString("dd-MM-yyyy HH:mm:ss")</text></p>
            </div>
        </div>
    </div>
    <br />
    <div>
        <table class="table">
            <tr class="font-weight-bold text-center text-secondary">
                <td style="width:20vw">Укороченая ссылка</td>
                <td style="width:40vw">Описание</td>
                <td style="width:10vw">Количество переходов</td>
                <td style="width:10vw">Дата создания</td>
                <td style="width:20vw"></td>
            </tr>
            @if (Model.Links != null)
            {
                @foreach (var item in Model.Links)
                {
                    string @urlString = Url.Action("RedirectToOldLink", "ShortLink", new { id = item.Id }, "https");
                    <tr class="text-black-50">
                        <td>
                            <new-link link-id="@item.Id">
                                @urlString
                            </new-link>
                        </td>
                        <td>@item.Description</td>
                        <td class="text-center">@item.UseCount</td>
                        <td class="text-center">@item.DateOfCreate.ToString("dd-MM-yyyy HH:mm:ss")</td>
                        <td class="row">
                            <div>
                                @if (item.IsPublic)
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка видна на главной странице" class="far fa-eye"></i>
                                    </button>
                                }
                                else
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка не видна на главной странице" class="far fa-eye-slash"></i>
                                    </button>
                                }
                            </div>
                            <div>
                                @if (item.IsActive)
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка активна" class="fas fa-toggle-on"></i>
                                    </button>
                                }
                                else
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка не активна" class="fas fa-toggle-off"></i>
                                    </button>
                                }
                            </div>
                            <button class="btn btn-link text-black-50">
                                <i title="Исходная ссылка: @item.OldLink" class="far fa-hand-point-down" ></i>
                            </button>
                            <button class="btn btn-link text-black-50">
                                <i title="Проект: @item.Project.Caption" class="far fa-folder"></i>
                            </button>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>


@section scripts
{
    <script type="text/javascript" src="~/js/MyScripts.js"></script>
}

src/ShortLinks.WebMVC/Views/Statistics/AllProjects.cshtml
@model ProjectStatisticsModel
@{
    ViewData["Title"] = "Статистика";
}

<div class="col">
    <br />
    <div class="text-center m-sm-1">
        <p class="display-4">Общая статистика по проектам</p>
        <p>В статистике представленны только ваши проекты, которые существуют на данный момент</p>
    </div>
    <br />
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <a class="btn-collapse " data-toggle="collapse" href="#generalInfo" role="button" aria-expanded="false" aria-controls="generalInfo">
                    Показать общую статистику <i class="fas fa-chevron-down"></i>
                </a>
            </h5>
        </div>
        <div class=" font-weight-bold collapse" id="generalInfo">
            <div class=" card-body">
                <p>Общее количество проектов: <text class="text-success">@Model.ProjectModels.Count</text> </p>
                <p>Общее количество ссылок: <text class="text-success">@Model.AmountCountLink</text> </p>
                <p>Общее количество открытых ссылок: <text class="text-success">@Model.AmountCountPublicLink</text></p>
                <p>Общее количество активных ссылок: <text class="text-success">@Model.AmountCountActiveLink</text></p>
                <p>Общее количество переходов: <text class="text-success">@Model.AmountUseCount</text></p>
            </div>
        </div>
    </div>
    <br />
    <div>
        <table class="table">
            <tr class="font-weight-bold text-center text-secondary">
                <td style="width:20vw">Название</td>
                <td style="width:20vw">Количество ссылок</td>
                <td style="width:20vw">Количество переходов</td>
                <td style="width:20vw">Количество общедоступных ссылок</td>
                <td style="width:20vw">Количество активных ссылок</td>
            </tr>
            @if (Model.ProjectModels != null)
            {
                @foreach (var item in Model.ProjectModels)
                {
                    <tr class="text-black-50">
                        <td>@item.Caption</td>
                        <td class="text-center">@item.CountLink</td>
                        <td class="text-center">@item.UseCount</td>
                        <td class="text-center">@item.CountPublicLink</td>
                        <td class="text-center">@item.CountActiveLink</td>
                    </tr>
                }
            }
        </table>
    </div>
</div>


@section scripts
{
    <script type="text/javascript" src="~/js/MyScripts.js"></script>
}

src/ShortLinks.WebMVC/Views/Statistics/LinksByProject.cshtml
@model LinkStatisticsModel
@{
    string projectName = Model.Links.ElementAt(0).Project.Caption;
    ViewData["Title"] = "Статистика";
}

<div class="col">
    <br />
    <div class="text-center m-sm-1">
        <p class="display-4">Общая статистика по проекту @projectName</p>
        <p>В статистике представленны только ваши ссылки из проекта, которые существуют на данный момент</p>
    </div>
    <br />
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <a class="btn-collapse " data-toggle="collapse" href="#generalInfo" role="button" aria-expanded="false" aria-controls="generalInfo">
                    Показать общую статистику <i class="fas fa-chevron-down"></i>
                </a>
            </h5>
        </div>
        <div class=" font-weight-bold collapse" id="generalInfo">
            <div class=" card-body">
                <p>Общее количество ссылок: <text class="text-success">@Model.LinkCount</text> </p>
                <p>Общее количество открытых ссылок: <text class="text-success">@Model.PublicLinkCount</text></p>
                <p>Общее количество активных ссылок: <text class="text-success">@Model.ActiveLinkCount</text></p>
                <p>Общее количество переходов: <text class="text-success">@Model.TotalUseAmount</text></p>
                <p>Время создания первой существующей ссылки: <text class="text-success">@Model.FirstLinkDate.ToString("dd-MM-yyyy HH:mm:ss")</text></p>
                <p>Время создания последней существующей ссылки: <text class="text-success">@Model.LastLinkDate.ToString("dd-MM-yyyy HH:mm:ss")</text></p>
            </div>
        </div>
    </div>
    <br />
    <div>
        <table class="table">
            <tr class="font-weight-bold text-center text-secondary">
                <td style="width:22vw">Укороченая ссылка</td>
                <td style="width:45vw">Описание</td>
                <td style="width:10vw">Количество переходов</td>
                <td style="width:10vw">Дата создания</td>
                <td style="width:13vw"></td>
            </tr>
            @if (Model.Links != null)
            {
                @foreach (var item in Model.Links)
                {
                    string @urlString = Url.Action("RedirectToOldLink", "ShortLink", new { id = item.Id }, "https");
                    <tr class="text-black-50">
                        <td>
                            <new-link link-id="item.Id">
                                @urlString
                            </new-link>
                        </td>
                        <td>@item.Description</td>
                        <td class="text-center">@item.UseCount</td>
                        <td class="text-center">@item.DateOfCreate.ToString("dd-MM-yyyy HH:mm:ss")</td>
                        <td class="row">
                            <div>
                                @if (item.IsPublic)
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка видна на главной странице" class="far fa-eye"></i>
                                    </button>
                                }
                                else
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка не видна на главной странице" class="far fa-eye-slash"></i>
                                    </button>
                                }
                            </div>
                            <div>
                                @if (item.IsActive)
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка активна" class="fas fa-toggle-on"></i>
                                    </button>
                                }
                                else
                                {
                                    <button class="btn btn-link text-black-50">
                                        <i title="Данная ссылка не активна" class="fas fa-toggle-off"></i>
                                    </button>
                                }
                            </div>
                            <button class="btn btn-link text-black-50">
                                <i title="Исходная ссылка: @item.OldLink" class="far fa-hand-point-down"></i>
                            </button>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>


@section scripts
{
    <script type="text/javascript" src="~/js/MyScripts.js"></script>
}

src/ShortLinks.WebMVC/Views/Statistics/Show.cshtml
@{
    ViewData["Title"] = "Статистика";

}

    <div>
        <div class="justify-content-center">
            <div class="text-center m-md-5 ">
                <h2>Выберите вид статистики для просмотра</h2>
                <p class=" text-black-50">В случае необходимости укажите дополнительные параметры!</p>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-4 offset-1 ">
                <div class="border border-secondary rounded " style="background: #e8e8e8">
                    <div class="p-md-3 pl-md-4 pr-md-4">
                        <br />
                        <label class="">Общая статистика по ссылкам</label>
                        <br />
                        <br />
                        <a asp-action="AllLinks" asp-controller="Statistics" class="btn btn-outline-primary">Выбрать</a>
                    </div>
                </div>
            </div>
            <div class="col-4 offset-2">
                <div class="border border-secondary  rounded " style="background: #e8e8e8">
                    <form asp-action="" asp-controller="">
                        <div class=" p-md-3 pl-md-4 pr-md-4">
                            <br />
                            <label class="">Общая статистика по проектам</label>
                            <br />
                            <br />
                            <a asp-action="AllProjects" asp-controller="Statistics" class="btn btn-outline-primary">Выбрать</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <div class="row text-center ">
            <div class="col-4 offset-1 ">
                <div class="border border-secondary rounded " style="background:#e8e8e8">
                    <form asp-action="LinksByProject" asp-controller="Statistics" method="get" asp-anti-forgery="true">
                        <div class="validation p-md-3 pl-md-4 pr-md-4">
                            <br />
                            <div>
                                <label class="">Статистика по проекту</label>
                                <br />
                                <small><label class="text-secondary">Выберите проект</label></small><br />
                                @Html.DropDownList("projectId", ViewBag.Projects as SelectList)
                            </div>
                            <br />
                            <div class="form-group text-center">
                                <input type="submit" value="Выбрать" class=" btn btn-outline-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-4 offset-2 align-content-center ">
                <div class="border border-secondary rounded " style="background:#e8e8e8">
                    <form asp-action="ShowDiagram" asp-controller="Statistics" method="get">
                        <div class="p-md-3 pl-md-4 pr-md-4">
                            <br />
                            <div class="form-group text-center">
                                <br />
                                <br />
                                <label class="">Отображение диаграммы</label>
                                <br />
                                <br />
                            </div>
                            <div class="form-group text-center">
                                <input type="submit" value="Выбрать" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

src/ShortLinks.WebMVC/Views/Statistics/ShowDiagram.cshtml
@model List<ShortLinks.BLL.Models.Link>
@{
    var step = (Model.ElementAt(0).UseCount / 5.0).ToString(System.Globalization.CultureInfo.CreateSpecificCulture("en-GB"));
    ViewData["Title"] = "Статистика";
}
<div style="font-family:Tahoma, Arial, Helvetica, sans-serif">
    <canvas id="Chart" width="400" height="200"></canvas>
</div>


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

@section scripts
{
    <script type="text/javascript">
        var captions = [];
        var useCount = [];
        @foreach (var link in Model)
        {
            @:captions.push('@link.Description [@link.Project.Caption](@link.DateOfCreate.ToShortDateString())');
            @:useCount.push('@link.UseCount');
        }

        var canvas = document.getElementById('Chart');
        var data = {
            labels: captions,
            datasets: [
                {
                    label: 'Количество переходов',
                    backgroundColor: "rgba(3, 223, 252, 0.2)",
                    borderColor: "rgba(3, 252, 161, 1)",
                    borderWidth: 2,
                    hoverBackgroundColor: "rgba(3, 202, 252, 0.4)",
                    hoverBorderColor: "rgba(0, 232, 135, 1)",
                    data: useCount,
                }
            ]
        };

        var myBarChart = Chart.Bar(canvas, {
            data: data,
            options: {
                responsive: true,
                legend: {
                    position: 'top',
                    onClick: null
                },
                title: {
                    display: true,
                    text: 'Диаграмма популярности ссылок',
                    fontSize: 35
                },
                scales: {
                    yAxes: [{ ticks: { stepSize: @step, beginAtZero: true, fontSize: 12, fontFamily: "'Lato', sans-serif", fontColor: '#005', fontStyle: '500' } }],
                    xAxes: [{ ticks: { fontSize: 12, fontFamily: "Tahoma, Arial, Helvetica, sans-serif", fontColor: '#005', fontStyle: '500' } }]
                }
            }
        });


    </script>
}