src/ShortLinks.WebMVC/Controllers/LinkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShortLinks.BLL.Services.Interfaces;
using ShortLinks.BLL.ViewModels;
using System.Threading.Tasks;

namespace ShortLinks.WebMVC.Controllers
{
    [Authorize]
    public class LinkController : Controller
    {
        private readonly ILinkService _linkService;
        private readonly IProjectService _projectService;
        private readonly IPersonalDataProtectionService _personalDataProtectionService;

        public LinkController(
            IProjectService projectService,
            ILinkService linkService,
            IPersonalDataProtectionService personalDataProtectionService)
        {
            _projectService = projectService;
            _linkService = linkService;
            _personalDataProtectionService = personalDataProtectionService;
        }

        public async Task<IActionResult> AllLinks()
        {
            return View(await _linkService.GetAllLinksAsync());
        }

        public IActionResult UserLinks()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Add(int projectId)
        {
            if (_personalDataProtectionService.IsUserHasProject(projectId, User))
            {
                var project = await _projectService.GetProjectAsync(projectId);
                ViewBag.Project = project;
                return View();
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Add(LinkModel model)
        {
            var projectId = await _linkService.AddLinkAsync(model);
            return RedirectToAction("Links", "Project", new { projectId });
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmDelete(int linkId)
        {
            if (_personalDataProtectionService.IsUserHasLink(linkId, User))
            {
                var link = await _linkService.GetLinkAsync(linkId);
                return PartialView(link);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int linkId)
        {
            //get link and id for link project
            var link = await _linkService.GetLinkAsync(linkId);
            var projectId = link.ProjectId;

            //delete link
            await _linkService.DeleteLinkAsync(link);

            return RedirectToAction("Links", "Project", new { projectId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int linkId)
        {
            if (_personalDataProtectionService.IsUserHasLink(linkId, User))
            {
                var link = await _linkService.GetLinkAsync(linkId);
                ViewBag.Link = link;
                return View();
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(LinkModel link)
        {
            await _linkService.SaveLinkAsync(link);
            return RedirectToAction("Links", "Project", new { projectId = link.ProjectId });
        }

        [HttpGet]
        public async Task<IActionResult> Move(int linkId)
        {
            if (_personalDataProtectionService.IsUserHasLink(linkId, User))
            {
                //create list of projects
                var list = _projectService.GetProjects(User);
                ViewBag.Projects = new SelectList(list, "Id", "Caption");

                var link = await _linkService.GetLinkAsync(linkId);
                return PartialView(link);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Move(int linkId, int projectId)
        {
            await _linkService.MoveLinkAsync(linkId, projectId);

            return RedirectToAction("Links", "Project", new { projectId });
        }

        [HttpGet]
        public async Task<IActionResult> ShowMine()
        {
            var links = await _linkService.FindMyLinksAsync(User);

            return View(await _linkService.GetLinksAndDefaulProjectModelAsync(links, User));
        }

    }
}

src/ShortLinks.WebMVC/Controllers/ShortLinkController.cs
using Microsoft.AspNetCore.Mvc;
using ShortLinks.BLL.Services.Interfaces;
using System.Threading.Tasks;

namespace ShortLinks.WebMVC.Controllers
{
    public class ShortLinkController : Controller
    {
        private readonly ILinkService _linkService;

        public ShortLinkController(ILinkService linkService)
        {
            _linkService = linkService;
        }

        [HttpGet]
        [Route("l")]
        public async Task<IActionResult> RedirectToOldLink(int id)
        {
            if (!await _linkService.IsLinkExistAsync(id))
            {
                return NotFound();
            }

            var link = await _linkService.GetLinkAsync(id);
            if (link.IsActive)
            {
                await _linkService.IncreaseInQuantityAsync(id);
                return Redirect(link.OldLink);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

src/ShortLinks.WebMVC/Views/Link/Add.cshtml
@model LinkModel
@{
    var project = ViewBag.Project;
    ViewData["Title"] = "Добавление ссылки";
}
<div class="row justify-content-center">
    <div class="col-md-5">
        <br />
        <br />
        <div>
            <h4 class="text-center">Добавление ссылки в проект <q><i>@project.Caption</i></q></h4>
        </div>
        <br />
        <div class="border border-secondary rounded bg-white p-4 m-3">
            <form asp-action="Add" asp-controller="Link" asp-anti-forgery="true">
                <div class="validation" asp-validation-summary="ModelOnly"/>
                <div class="form-group">
                    <label asp-for="OldLink" class="control-label text-secondary small">Ссылка для перехода</label><br />
                    <input type="text" asp-for="OldLink" size="48" />
                    <span  class="text-danger small" asp-validation-for="OldLink" />
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label text-secondary small">Описание</label><br />
                    <textarea asp-for="Description" cols="50" rows="5"></textarea>
                    <span  class="text-danger small" asp-validation-for="Description" />
                </div>
                <div class="">
                    <label asp-for="IsActive" class="control-label text-secondary small">Активность ссылки - </label>
                    <input type="checkbox" asp-for="IsActive" checked class="" value="true" />
                    <input type="hidden" asp-for="IsActive" value="false" />
                </div>
                <div class="">
                    <label asp-for="IsPublic" class="control-label text-secondary small">Данную ссылка могут видеть другие пользователи сайта - </label>
                    <input type="checkbox" asp-for="IsPublic" checked class="" value="true" />
                    <input type="hidden" asp-for="IsPublic" value="false" />
                </div>
                <div>
                    <input type="hidden" asp-for="ProjectId" value="@project.Id" />
                </div>
                <br />
                <div class="form-group row justify-content-around">
                    <div class="ml-sh-5">
                        <input type="submit" value="Добавить" class="btn btn-outline-primary" />
                    </div>
                    <div>
                        <button onclick="JavaScript:window.history.back(1); return false;" class="btn btn-outline-warning">Отмена</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts
{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/ShortLinks.WebMVC/Views/Link/ConfirmDelete.cshtml
@model Link
@{
    Layout = null;
}
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="text-sm-secondary text-sm-center">Подтвердите действие</h4>
        </div>
        <div class="modal-body">
            <br />
            <dl class="dl-horizontal">
                <dt class="text-sm-center">
                    Вы действительно хотите удалить ссылку @Model.Id
                    <br />
                    с описанием <q>@Model.Description</q>
                </dt>
            </dl>
            <br />
        </div>
        <div class="modal-footer">
            <div class=" container">
                <div class="form-group d-flex justify-content-sm-around">
                    <form method="post" asp-action="Delete" asp-controller="Link" asp-route-linkId="@Model.Id">
                        <input type="submit" value="Удалить" class="btn btn-outline-danger">
                    </form>
                    <button type="button" class="btn btn-outline-success" data-dismiss="modal">Отменить </button>
                </div>
            </div>
        </div>
    </div>

src/ShortLinks.WebMVC/Views/Link/Edit.cshtml
@model LinkModel
@{
    Link link = ViewBag.Link;
    ViewData["Title"] = "Редактирование ссылки";
}
<div class="row justify-content-center">
    <div class="col-md-5">
        <br />
        <br />
        <div>
            <h4 class="text-center">Изменение ссылки  <q><i>@link.Id</i></q></h4>
        </div>
        <br />
        <div class="border border-secondary rounded bg-white p-4 m-3">
            <form asp-action="Edit" asp-controller="Link" asp-anti-forgery="true">
                <div class="validation" asp-validation-summary="ModelOnly" />
                <div class="form-group">
                    <label asp-for="OldLink" class="control-label text-secondary small">Ссылка для перехода</label><br />
                    <input type="text" asp-for="OldLink" value="@link.OldLink" size="48" />
                    <span class="text-danger small" asp-validation-for="OldLink" />
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label text-secondary small">Описание</label><br />
                    <textarea for="Description" name="Description" cols="50" rows="5">@ViewBag.Link.Description </textarea>
                    <span class="text-danger small" asp-validation-for="Description" />
                </div>
                <div class="">
                    <label asp-for="IsActive" class="control-label text-secondary small">Активность ссылки - </label>
                    @if (link.IsActive)
                    {
                        <input type="checkbox" checked asp-for="IsActive" value="true" />
                    }
                    else
                    {
                        <input type="checkbox" asp-for="IsActive" value="true" />
                    }
                    <input type="hidden" asp-for="IsActive" value="false" />
                </div>
                <div class="">
                    <label asp-for="IsPublic" class="control-label text-secondary small">Данную ссылка могут видеть другие пользователи сайта - </label>
                    @if (link.IsPublic)
                    {
                        <input type="checkbox" checked asp-for="IsPublic" class="" value="true" />
                    }
                    else
                    {
                        <input type="checkbox" asp-for="IsPublic" class="" value="true" />

                    }
                    <input type="hidden" asp-for="IsPublic" value="false" />
                </div>
                <div>
                    <input type="hidden" asp-for="Id" value="@link.Id" />
                    <input type="hidden" asp-for="ProjectId" value="@link.ProjectId" />
                </div>
                <br />
                <div class="form-group row justify-content-around">
                    <div class="ml-sh-5">
                        <input type="submit" value="Изменить" class="btn btn-outline-primary" />
                    </div>
                    <div>
                        <button onclick="JavaScript:window.history.back(1); return false;" class="btn btn-outline-warning">Отмена</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts
{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/ShortLinks.WebMVC/Views/Link/Move.cshtml
@model Link
@{
    Layout = null;
}
<div class="modal-content">
    <div class="modal-header">
        <h4 class="text-sm-secondary text-sm-center">Выберите проект</h4>
    </div>
    <div class="modal-body">
        <br />
        <dl class="dl-horizontal">
            <dt class="text-sm-center">
                Выберите проект для перемещения ссылки
                <br />
                с описанием <q>@Model.Description</q>
            </dt>
        </dl>
        <div class=" container">
            <form method="post" asp-action="Move" asp-controller="Link">
                <div class=" d-flex justify-content-sm-center">
                    @Html.DropDownList("projectId", ViewBag.Projects as SelectList)
                    <input type="hidden" name="linkId" value="@Model.Id">
                </div>
                <br />
                <br />

                <div class=" container">
                    <div class="d-flex justify-content-sm-around">
                        <div>
                            <input type="submit" value="Переместить" class="btn btn-outline-primary">
                        </div>
                        <div>
                            <input type="button" value="Отменить" class="btn btn-outline-warning" data-dismiss="modal">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

src/ShortLinks.WebMVC/Views/Link/ShowAll.cshtml
@model LinksAndDefaultProjectModel
@{
    ViewData["Title"] = "Все ссылки";
}
<div class="col">
    <br />
    <div class="text-center m-sm-1">
        <p class="display-4">
            Все зарегестрированные ссылки
        </p>
        @if (User.Identity.IsAuthenticated)
        {
            <p>
                <a asp-action="Add" asp-controller="Link" asp-route-projectId="@Model.Project.Id">Добавить</a> ссылку в проект по умолчанию.
            </p>
        }
    </div>
    <br />
    <div>
        <table class="table">
            <tr class="font-weight-bold text-center text-secondary">
                <td style="width:30vw">Укороченая ссылка</td>
                <td style="width:45vw">Описание</td>
                <td style="width:10vw">Дата создания</td>
                <td style="width:15vw"></td>
            </tr>
            @foreach (var item in Model.Links)
            {
                string @urlString = Url.Action("RedirectToOldLink", "ShortLink", new { id = item.Id }, "https");
                <tr class="text-black-50">
                    <td>
                        <new-link link-id="@item.Id">
                            @urlString
                        </new-link>
                    </td>
                    @{ 
                    //получить href ссылки и передать для копирования
                    }
                    <td>@item.Description</td>
                    <td class="text-center">@item.DateOfCreate.ToString("dd-MM-yyyy HH:mm:ss")</td>
                    <td class="row">
                        <div>
                            @if (item.IsActive)
                            {
                                <button class="btn btn-link text-black-50">
                                    <i title="Данная ссылка активна" class="fas fa-toggle-on"></i>
                                </button>
                            }
                            else
                            {
                                <button class="btn btn-link text-black-50">
                                    <i title="Данная ссылка не активна" class="fas fa-toggle-off"></i>
                                </button>
                            }
                        </div>
                        <button class="btn btn-link text-black-50">
                            <i title="Исходная ссылка(для копирования щёлкните по иконке): @item.OldLink" class="far fa-hand-point-down zoom" onclick='javascript: navigator.clipboard.writeText("@item.OldLink")'></i>
                        </button>
                        <button class="btn btn-link text-black-50" onclick='javascript: navigator.clipboard.writeText("@urlString")'>
                            <i title="Копировать" class="far fa-copy zoom"></i>
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

src/ShortLinks.WebMVC/Views/Link/ShowMine.cshtml
@model LinksAndDefaultProjectModel
@{

    ViewData["Title"] = "Мои ссылки";
}
<div class="col">
    <br />
    <div class="text-center m-sm-1">
        <p class="display-3">
            Мои ссылки
        </p>
        <p>
            <a asp-action="Add" asp-controller="Link" asp-route-projectId="@Model.Project.Id">Добавить</a> ссылку в проект по умолчанию.
        </p>
    </div>
    <br />
    <div>
        <table class="table">
            <tr class="font-weight-bold text-center text-secondary">
                <td style="width:25vw">Укороченая ссылка</td>
                <td style="width:32vw">Описание</td>
                <td style="width:10vw">Дата создания</td>
                <td style="width:33vw"></td>
            </tr>
            @foreach (var item in Model.Links)
            {
                string @urlString = Url.Action("RedirectToOldLink", "ShortLink", new { id = item.Id }, "https");
                <tr class="text-black-50">
                    <td>
                        <new-link id="link_@item.Id" link-id="@item.Id">
                            @urlString
                        </new-link>
                    </td>
                    <td>@item.Description</td>
                    <td class="text-center">@item.DateOfCreate.ToString("dd-MM-yyyy HH:mm:ss")</td>
                    <td class="row">
                        <div>
                            @if (item.IsPublic)
                            {
                                <button class="btn btn-link text-black-50">
                                    <i title="Данная ссылка видна на главной странице" class="far fa-eye"></i>
                                </button>
                            }
                            else
                            {
                                <button class="btn btn-link text-black-50">
                                    <i title="Данная ссылка не видна на главной странице" class="far fa-eye-slash"></i>
                                </button>
                            }
                        </div>
                        <div>
                            @if (item.IsActive)
                            {
                                <button class="btn btn-link text-black-50">
                                    <i title="Данная ссылка активна" class="fas fa-toggle-on"></i>
                                </button>
                            }
                            else
                            {
                                <button class="btn btn-link text-black-50">
                                    <i title="Данная ссылка не активна" class="fas fa-toggle-off"></i>
                                </button>
                            }
                        </div><button class="btn btn-link text-black-50">
                            <i title="Проект: @item.Project.Caption" class="far fa-folder"></i>
                        </button>
                        <button class="btn btn-link text-black-50">
                            <i title="Исходная ссылка(для копирования щёлкните по иконке): @item.OldLink" class="far fa-hand-point-down zoom" onclick='javascript: navigator.clipboard.writeText("@item.OldLink")'></i>
                        </button>
                        <button class="btn btn-link text-black-50" onclick='javascript: navigator.clipboard.writeText("@urlString")'>
                            <i title="Копировать" class="far fa-copy zoom"></i>
                        </button>
                        <button class="btn btn-link ">
                            <a asp-action="Edit" asp-controller="Link" asp-route-linkId="@item.Id" class="text-black-50 ">
                                <i title="Изменить" class="far fa-edit zoom"></i>
                            </a>
                        </button>
                        <div id="modDialogDelete" class="modal fade">
                            <div id="dialogContentDelete" class="modal-dialog"></div>
                        </div>
                        <button class="btn btn-link ">
                            <a asp-action="ConfirmDelete" asp-controller="Link" asp-route-linkId="@item.Id" class="text-black-50 delItem ">
                                <i title="Удалить" class="fas fa-trash zoom"> </i>
                            </a>
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

@section scripts
{
    <script type="text/javascript" src="~/js/MyScripts.js"></script>
}